#-----------------------------------------------------------------------------
# Jenkins location and login credentials.
jenkins:  http://jenkins.yourdomain.com
username: None  # optional
password: None  # optional

#-----------------------------------------------------------------------------
# Svn base url (not necessarily the repository root).
repo: file:///tmp/repo/

#-----------------------------------------------------------------------------
# Urls to list for branches that will be matchable by the refs option.
# Autojobs will 'svn ls' each of these and strip the value of 'repo'.
branches:
  - file:///tmp/repo/branches/
  - file:///tmp/repo/experimental/
  - file:///tmp/repo/releases/

#-----------------------------------------------------------------------------
# Repository login credentials.
scm-username: None  # optional
scm-password: None  # optional

#-----------------------------------------------------------------------------
# Job to use as a template for new jobs.
template: new-job-template

#-----------------------------------------------------------------------------
# Character with which to replace '/' in branch names.
namesep: '-'

#-----------------------------------------------------------------------------
# Template string to use for new job names. Several placeholder variables as
# well as regex capture groups and backreferences from the 'refs' match are
# available. Given a branch 'branches/svn-bisect' and a regex
# 'branches/(.*)-(.*)', the following placeholders will be available:
#
#   {path}       branches-svn-bisect
#   {path-orig}  branches/svn-bisect
#   {branch}     svn-bisect
#   {0}          svn
#   {1}          bisect
#
# The default is '{path}'.
namefmt: '{path}'


#-----------------------------------------------------------------------------
# If false, a job will never be overwritten if it exists.
# If true, a job will be overwritten if the new configration differs from the
# old one (the default).
overwrite: true

#-----------------------------------------------------------------------------
# State of newly created or overwritten jobs. Default is 'sticky'. One of:
#   true       -> Jobs will be enabled.
#   false      -> Jobs will be disabled.
#   'template' -> Jobs will inherit the state of their template job.
#   'sticky'   -> New jobs inherit the state of the template job -
#                 overwritten jobs keep their most recernt state.
enable: 'sticky'

#-----------------------------------------------------------------------------
# Makes text substitutions throughout all text elements of a job’s config.xml.
# This includes the body of all commands that you may have defined. This option
# is useful for plugins that cannot introspect the name of the branch or job
# themselves (e.g. Sidebar-Link). All placeholders available to the namefmt
# option are also available here.
substitute:
  '@@JOB_NAME@@': '{branch}'
  '@@REF_NAME@@': 'ref-{shortref}'
  '@@STORAGE@@':  '/storage/builds/'

#-----------------------------------------------------------------------------
# Substitutions to perform on the ref and shortref.
# The default is '@!?#&|\^_$%*': '_', which substitutes the characters
# that cannot be in a Jenkins job name with '_'.
sanitize:
  '@!?#&|\^_$%*': '_'    # replace any of @!?#&|\^_$%* with _
  're:colou?r': 'color'  # replace regex 'colou?r' with 'color'

#-----------------------------------------------------------------------------
# List of branches to ignore (regular expressions).
ignore:
  - 'branches/.*-nobuild'
  - 'experimental/john/.*'

#-----------------------------------------------------------------------------
# A list of regular expressions that specify which refs to process.
# Global settings can be overwritten on a per-branch basis.
# Defaults to all branches ('refs: ".*"').
refs:
  - 'branches/(.*)'
  - 'releases/(.*)':
      'template': 'release-template'
      'namefmt':  'release-{short}'
      'enable':   false
      'view':     'release-view'
      'tag':      'group-1'

#-----------------------------------------------------------------------------
# View to which new jobs should be added. Cannot be 'All'.
view: 'view-name'

#-----------------------------------------------------------------------------
# Tag jobs with this string. The tag will be placed inside the config.xml of
# new or updated jobs under the 'createByJenkinsAutojobs/tag' element.
tag: 'throw-away-jobs'

#-----------------------------------------------------------------------------
# If set to true, jenkins-autojobs will remove jobs for branches that were
# deleted. It uses a special property in the job’s config.xml to determine if
# the job was created by jenkins-autojobs.
#
# If set to a tag name, only jobs with that name will be cleaned. This is
# useful if you have more than one instance of jenkins-autojobs running and you
# don’t want them to mutually cleanup each others jobs.
cleanup: true  # or 'throw-away-jobs'
